### PR TITLE
35 swipe dash replacement

### LINKED ISSUE #35: Swipe/Dash Replacement
Replacing the universal mechanic of melee arm swings with a short dash that serves the same purpose towards the ball.
This will involve:

- [ ] Removal of "Basic Swing" scripts from the default player assets

- [ ] Editing basic dash script to no longer be an ability, re-bind it to the "swing" binding

- [ ] Rename "swing" terminology to something like "basic attack" or "dash"

- [ ] Implement new animations to show dash in default character

- [ ] Add cinemachine & particle effects on hitting the ball with a dash (maybe hitstop?)

### PR DESCRIPTION
**Pull request by jackosullivan88**
**Changes:**
- Removed some scripts no longer in use relating to "slash" system
- Changed variable names to reflect the change to "dash" as universal mechanic
- Removed "Ability" attribution from dash script
- Revised "dash" script to include motion dynamics
- Added Animation Curve to dash script to easily alter dynamics on a per-prefab basis
- Added placeholder dash animation to default player character
- Altered hitbox object to function with dash mechanic
- Altered default player Animator tree to reflect change to dash

**Known Bugs:**
- Dash hitbox will sometimes not disappear. I've implemented a fix that has not yet failed, but in case it shows up again this has to do with the transition from "dash" animation back to the default state, it's skipping over the animation event that disables the hitbox for some reason. Again, it _appears_ to be fixed but just in case it rears its head again I thought I should mention it here.
- Ball will occasionally encounter a significant drop in velocity when hit, either slowing to a crawl or appearing to not move at all. I've noticed this occurring primarily when the ball is hit in the exact opposite direction that it's currently moving in. I suspect the collision with the hitbox is cancelling out whatever speed the ball had in the opposite direction and not adding to it. This bug existed with the previous "swing" mechanic as well.

### CODE REVIEW

**Review by Gerald-R-M — CHANGES_REQUESTED** [review]
The changes themselves are great! However, I'd like more comments in your code to help us in the future should we need to do any sort of bug fixing

**Review by Gerald-R-M — APPROVED** [review]
New comments look great! Thank you for the addition and thanks in advance for that documentation for the wiki!

**Comment by MattMcL1221** [comment]
Dash looks good but the game feel seems like it could be improved. If we gave it a bit more start-up acceleration or decreased friction on movement it could feel better to dash around. Maybe also a very small amount of less ending lag to move out of it quicker? Your player kinda stands still momentarily after using it but at the same time we don't want people spamming.

Also, the ball is still capable of slowing down, we need to either make this a full mechanic of being able to slow the ball by hitting it in a certain way/with certain hitboxes or lock the ball's speed so It can only increase. Right now it seems a bit RNG when hit.

This is unrelated to the dash but with the ball we might want initial hit acceleration to be lowered quite a bit. In the Prototype Arena you currently get knocked across 75% of the Arena's Width with a single hit from the ball which seems way too much for the first hit of the game.

**Review by MattMcL1221 — APPROVED** [review]
Approved but Double Check if files are somehow already in Main?

**Pull request merged**
